# Docker in docker
image: docker:18.06.3
services:
  - docker:18.06.3-dind
variables:
  DOCKER_HOST: tcp://localhost:2375
before_script:
  - echo $CI_JOB_ID
  - echo "Building $CI_REGISTRY_IMAGE ..."

stages:
  - build

build:
  image: ubuntu:19.10
  cache:
    paths:
      - ../.m2/repository/
  variables:
    MAVEN_CLI_OPTS: "-s ../.m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=../.m2/repository"
  stage: build
  script:
    - apt update && apt install -y openjdk-13-jdk maven
    - cd code
    - mvn -DskipTests -U $MAVEN_CLI_OPTS -Dgit.branch=$CI_COMMIT_REF_NAME -Ddocker.registry=$CI_REGISTRY_IMAGE clean deploy
